### PR TITLE
language support

### PR DESCRIPTION
**Pull request by bmonninkhof**
I would like to see the Dutch language to the security app. I would like to help translate the app into the Dutch language.
How can I contribute to this app?

### CODE REVIEW

**Comment by MiguelRipoll23** [comment]
Hey there!

The only area that can be translated is the audio language (for the voice warnings in case you're using an speaker), would you like to help with the Dutch translation?

Plugin settings unfortunately can't be translated AFAIK.

Thanks 🙂

**Comment by MiguelRipoll23** [comment]
These are the audio warning messages that are available in English and German, would you like to help translate them to Dutch as well?

- Arming security system to Home mode
- Arming security system to Night mode
- Arming security system to Away mode
- Security system armed to Home mode
- Security system armed to Away mode
- Security system armed to Night mode
- Heads up! Security system is about to trigger
- Alarm triggered
- Security system disarmed

Thanks!

**Comment by bmonninkhof** [comment]
I don’t think my voice is suitable audio 😬. I can try…
With kind regards
Brian

Verstuurd vanaf mijn iPhone

Op 6 jun. 2021 om 16:59 heeft Miguel Ripoll ***@***.***> het volgende geschreven:

﻿

These are the audio warning messages that are available in English and German, would you like to help translate them to Dutch as well?

  *   Arming security system to Home mode
  *   Arming security system to Night mode
  *   Arming security system to Away mode
  *   Security system armed to Home mode
  *   Security system armed to Away mode
  *   Security system armed to Night mode
  *   Heads up! Security system is about to trigger
  *   Alarm triggered
  *   Security system disarmed

Thanks!

**Comment by MiguelRipoll23** [comment]
Sorry for the confusion, I meant that you could translate the texts and then it would be converted to speech using Google's Text-to-Speech by one of the many voices that they provide 😅

**Pull request closed without merging**
