### PR TITLE
Add update-state webhook option.

### LINKED ISSUE #14: Add ability to update state with webhook
Hey, Awesome plugin, thanks for your work :-)
I would like to be able to change the displayed state of the security system in homekit when it changes from another source.
Is there any solution to expose a server with some endpoints triggered by an external service to change the state?
Example: I have a hardware button to enable/disable the alarm but the state is not reported to homekit. The only action available is a webhook triggered by an online service when it detect a state change on my alarm.
It would be a nice feature!

### PR DESCRIPTION
**Pull request by funkyremi**
Hey, I made a PR that closes #14

### CODE REVIEW

**Comment by MiguelRipoll23** [comment]
I’ll test this as soon as possible tomorrow, thank you 🙏

**Comment by funkyremi** [comment]
Thank you 😊 can’t wait to see my 🚨 working perfectly with home app 🎉

**Comment by MiguelRipoll23** [comment]
Turns out that the quick fix broke the ability to trigger the security system so I added a second endpoint just to fix that and some improvements.

-  [New] Endpoint `sensor/triggered` to trigger remotely.
- [Fix] State update endpoint is now `target-state/<new_state>` to match the name of the characteristic from HomeKit.
- [Fix] States send from remote are now saved correctly.

If no more bugs are discovered this can be merged tomorrow for a new release 😛

**Comment by funkyremi** [comment]
There's an infinite loop issue. Every time my alarm state change, an event will be fired from a distant service and call the homebridge callback url to inform about the new state. So if I change the state, the state will be updated on the alarm, then the distant service will call the URL to inform about the new state and homebridge will the this state again and so on...

**Comment by funkyremi** [comment]
I made a commit that fix a 'valid state' bad value and add new route to update only the display state. The route is not working as expected, I don't know why. Nothing happens in home app when I call this URL. Have you got an idea to fix this?

**Comment by MiguelRipoll23** [comment]
Oops, thanks for then fix.

Yeah, the issue is that you are updating the current state. You have to update the target state first, then the current state. I’d use the `/target-state` Instead as it has added functionality to handle multiple scenarios like the security system being triggered. If what you want to do is update the state immediately when requested by your server (without the timeout) we can override that too, just let me know.

The infinite loop issue you’re describing is probably due to how the “webhooks” feature is implemented, I’ll fix this as soon as I can.

**Comment by funkyremi** [comment]
Yes that's exactly what I would like :-)

**Comment by funkyremi** [comment]
Here are the two scenarios:

1. I change the alarm state with the alarm remote:
* The alarm state is changed
* The distant alarm service call the specified homebridge URL with the new current state
* Homebridge receive the new state and update it in home app

2. I change the alarm state with my iphone:
* The proxy URL is called
* The alarm state change
* Homebridge update the state in home app


For the first case, homebridge should not call the proxy URL to avoid infinite loops.

For the second case, homebridge should not update the display state if the current state is already good to avoid receiving home notifications about alarm state change.

**Comment by MiguelRipoll23** [comment]
Now webhooks work correctly and shouldn't create infinite loops.

1. Request from client is received to change the target state.
2. Current state changes immediately for non-HomeKit requests.
3. Webhook event is sent with the current state.

**Comment by MiguelRipoll23** [comment]
The `url` option is now `webhooks_url` to clarify the intent and I changed the endpoint `/sensor/triggered` to `/triggered` to trigger the security system intermediately too.

**Comment by funkyremi** [comment]
Now the state is correctly changed but it seems like the plugin still call the webhook url after calling `/target-state` route.

**Comment by funkyremi** [comment]
Are you sure you want to change the `url` name? This is a breaking change for users that already uses the plugin.

**Comment by MiguelRipoll23** [comment]
Webhooks are used to notify that the current state has changed to an external server, what is your use case for them?

While this is a breaking change, it will be noted on the new release changelog for sure!

**Comment by MiguelRipoll23** [comment]
If you only need to update the state from an external server, you can remove the webhooks option from your config.

If the request was replied with a 200 status, the state was changed correctly.

**Comment by funkyremi** [comment]
I use webhooks to control my alarm. So when the webhook `path_away` is called, it really change the state of my alarm to `armed`.
The alarm also have an option to call webhooks when the state changes. That's why I wanted a server that listen to state changes to display it immediately in home app.
So I need both webhooks and server options.

**Comment by MiguelRipoll23** [comment]
Oh, I see now.

We can make it more simple. I send the webhook event when I'm about to update the current state and if you reply me with a 200 the state is updated, otherwise not.

1. You set a mode on the Home app.
2. Webhook sent to yours when arming time ends.
3. You reply me a 200 status
4. Current state is updated due to your reply.
5. If no reply is sent from yours, display no response error.

**Comment by funkyremi** [comment]
Ok but will it work if I change the state with my alarm remote? It needs to call the homebridge webhook to inform about the new state of the alarm.

**Comment by MiguelRipoll23** [comment]
Then it wouldn’t, it would just create another infinite loop :(

I’m not sure how to fix this, would not sending webhook events when changing modes using the server do it?

Sorry for the confusion.

**Comment by MiguelRipoll23** [comment]
Then it wouldn’t, it would just create another infinite loop :(

I’m not sure how to fix this, would not sending webhook events when changing modes using the server do it?

Sorry for the confusion.

**Comment by MiguelRipoll23** [comment]
Then it wouldn’t, it would just create another infinite loop :(

I’m not sure how to fix this, would not sending webhook events when changing modes using the server do it?

Sorry for the confusion.

**Comment by funkyremi** [comment]
You don't have a workaround to make it work?

**Comment by MiguelRipoll23** [comment]
That’s the only thing I’ve on my mind, I’m not sure if it would work or just create another loop if called differently.

**Comment by funkyremi** [comment]
I'll investigate a bit more when I have time. Thanks :-)

**Pull request merged**
